"""add fuel_types and fuel_prices tables, update devices fuel fields

Revision ID: 2c9ef6bb9f45
Revises: 5efbce0f7df1
Create Date: 2026-08-03 13:11:56.253990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c9ef6bb9f45'
down_revision: Union[str, Sequence[str], None] = '5efbce0f7df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fuel_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuel_type_id', sa.Integer(), nullable=False),
    sa.Column('price_per_liter', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuel_type_id', 'effective_date', name='uq_fuel_price_type_date')
    )
    op.add_column('devices', sa.Column('fuel_type_id', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('fuel_avg_running', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('fuel_avg_idle', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('fuel_avg_idle_auto', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'devices', 'fuel_types', ['fuel_type_id'], ['id'])
    op.drop_column('devices', 'fuel_type')
    op.drop_column('devices', 'avg_consumption_kmpl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('avg_consumption_kmpl', mysql.FLOAT(), nullable=True))
    op.add_column('devices', sa.Column('fuel_type', mysql.ENUM('petrol', 'diesel'), nullable=True))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'fuel_avg_idle_auto')
    op.drop_column('devices', 'fuel_avg_idle')
    op.drop_column('devices', 'fuel_avg_running')
    op.drop_column('devices', 'fuel_type_id')
    op.drop_table('fuel_prices')
    op.drop_table('fuel_types')
    # ### end Alembic commands ###
