"""add vehicle_type, plate_number, fuel_type, avg_consumption_kmpl to devices

Revision ID: 5efbce0f7df1
Revises: 93f3575614b4
Create Date: 2026-08-03 10:22:18.163244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efbce0f7df1'
down_revision: Union[str, Sequence[str], None] = '93f3575614b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('vehicle_type', sa.String(length=30), nullable=True))
    op.add_column('devices', sa.Column('plate_number', sa.String(length=30), nullable=True))
    op.add_column('devices', sa.Column('fuel_type', sa.Enum('petrol', 'diesel', name='fuel_type_enum'), nullable=True))
    op.add_column('devices', sa.Column('avg_consumption_kmpl', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'avg_consumption_kmpl')
    op.drop_column('devices', 'fuel_type')
    op.drop_column('devices', 'plate_number')
    op.drop_column('devices', 'vehicle_type')
    # ### end Alembic commands ###
