"""add geofences, trips tables, device primary_geofence_id

Revision ID: 782699ebae1c
Revises: 0b82c900ed88
Create Date: 2026-08-05 12:08:48.995585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782699ebae1c'
down_revision: Union[str, Sequence[str], None] = '0b82c900ed88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geofences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lon', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('geofence_id', sa.Integer(), nullable=False),
    sa.Column('trip_date', sa.Date(), nullable=False),
    sa.Column('trip_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', name='trip_status_enum'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=False),
    sa.Column('start_lon', sa.Float(), nullable=False),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('end_lon', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('driving_fuel_liters', sa.Float(), nullable=True),
    sa.Column('idle_fuel_liters', sa.Float(), nullable=True),
    sa.Column('total_fuel_liters', sa.Float(), nullable=True),
    sa.Column('price_per_liter_used', sa.Float(), nullable=True),
    sa.Column('fuel_cost_pkr', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'trip_date', 'trip_number', name='uq_trip_device_date_number')
    )
    op.add_column('devices', sa.Column('primary_geofence_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_devices_primary_geofence_id', 'devices', 'geofences', ['primary_geofence_id'], ['id'])    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_devices_primary_geofence_id', 'devices', type_='foreignkey')
    op.drop_column('devices', 'primary_geofence_id')
    op.drop_table('trips')
    op.drop_table('geofences')
    # ### end Alembic commands ###
