"""add last_seen_at, device_type, is_gps_anomaly, motion_status, device_alerts

Revision ID: 7d73ca9ce284
Revises: 1a735ebc86cb
Create Date: 2026-07-30 15:27:09.656334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d73ca9ce284'
down_revision: Union[str, Sequence[str], None] = '1a735ebc86cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'device_type')
    # ### end Alembic commands ###
