"""add trip driving-behavior metrics (max_speed_kmh, harsh_brake_count,
harsh_accel_count, overspeed_count, idle_count)

Revision ID: a1c3f8e2b7d4
Revises: 782699ebae1c
Create Date: 2026-08-06 07:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c3f8e2b7d4'
down_revision: Union[str, Sequence[str], None] = '782699ebae1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('max_speed_kmh', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('harsh_brake_count', sa.Integer(), nullable=True))
    op.add_column('trips', sa.Column('harsh_accel_count', sa.Integer(), nullable=True))
    op.add_column('trips', sa.Column('overspeed_count', sa.Integer(), nullable=True))
    op.add_column('trips', sa.Column('idle_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'idle_count')
    op.drop_column('trips', 'overspeed_count')
    op.drop_column('trips', 'harsh_accel_count')
    op.drop_column('trips', 'harsh_brake_count')
    op.drop_column('trips', 'max_speed_kmh')
    # ### end Alembic commands ###