"""replace is_moving boolean with motion_status enum

Revision ID: d632a52476db
Revises: f0e6640c840a
Create Date: 2026-07-30 12:38:34.563179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd632a52476db'
down_revision: Union[str, Sequence[str], None] = 'f0e6640c840a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_positions', sa.Column('is_gps_anomaly', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_positions', 'is_gps_anomaly')
    # ### end Alembic commands ###
