"""replace is_moving boolean with motion_status enum

Revision ID: f0e6640c840a
Revises: 05f1d863ec15
Create Date: 2026-07-30 12:05:15.448370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f0e6640c840a'
down_revision: Union[str, Sequence[str], None] = '05f1d863ec15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_positions', sa.Column('motion_status', sa.Enum('moving', 'idle', 'stopped', name='motion_status_enum'), nullable=False))
    op.drop_column('device_positions', 'is_moving')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_positions', sa.Column('is_moving', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('device_positions', 'motion_status')
    # ### end Alembic commands ###
